# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Build formats (PDF and ePub in addition to HTML)
formats:
  - pdf
  - epub

# Python configuration
python:
  version: "3.10"
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
    - requirements: docs/requirements.txt

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Install system dependencies if needed
      - echo "Installing system dependencies..."
    post_build:
      # Run any post-build tasks
      - echo "Documentation build complete!"

# Submodules (if you have any git submodules)
submodules:
  include: []
  recursive: false
